name: Run Test cases

on:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          export PATH="/root/.local/bin:$PATH"
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry==1.4
          poetry install
      - name: Test with pytest
        run: |
          pipx run poetry run pytest
